<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:property name="PI" value="3.1415927"/>
<material name="black">
    <color rgba="0 0 0 1"/>
</material>

<xacro:property name="base_footprint_radius" value="0.001"/>
<xacro:property name="base_link_radius" value="0.1"/>
<xacro:property name="base_link_length" value="0.08"/>
<xacro:property name="earth_space" value="0.015"/>
<xacro:property name="base_mass" value="2"/>

<link name="base_footprint">
<visual>
  <geometry>
    <sphere radius="${base_footprint_radius}"/>
  </geometry>
</visual>
</link>


<link name="base_link">
<visual>
  <geometry>
    <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
<material name="yellow"/>
</visual>
<collision>
    <geometry>
          <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
    </geometry>
     <origin xyz="0 0 0" rpy="0 0 0"/>
</collision>
<xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_link_radius}" h="${base_link_length}"/>
<gazebo reference="base_link"> 
  <material>Gazebo/Yellow</material>
</gazebo>
</link>


<joint name="base_link2base_footprint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 ${base_link_length/2+earth_space}"/>
</joint>



<xacro:property name="wheel_radius" value="0.0325"/>
<xacro:property name="wheel_length" value="0.015"/>
<xacro:property name="wheel_joint_z" value="${-earth_space-base_link_length/2+wheel_radius}"/>
<xacro:property name="wheel_mass" value="0.05"/>
<xacro:macro name="wheel_func" params="wheel_name flag">


<link name="${wheel_name}_wheel">
<visual>
  <geometry>
    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
  <material name="black"/>
</visual>

<collision>
  <geometry>
    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
</collision>
<xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
<gazebo reference="${wheel_name}_wheel"> 
  <material>Gazebo/Red</material>
</gazebo>



</link>

<joint name="${wheel_name}_wheel2base_link" type="continuous">
<parent link="base_link"/>
  <child link="${wheel_name}_wheel"/>
  <origin xyz="0 ${0.1*flag} ${wheel_joint_z}"/>
  <axis xyz="0 1 0"/>
</joint>
</xacro:macro>

<xacro:wheel_func wheel_name="left" flag="1"/>
<xacro:wheel_func wheel_name="right" flag="-1"/>



<xacro:property name="small_wheel_radius" value="0.0075"/>
<xacro:property name="small_joint_z" value="${(base_link_length/2+earth_space-small_wheel_radius)*(-1)}"/>
<xacro:property name="small_wheel_mass" value="0.01"/>

<xacro:macro name="small_wheel_func" params="small_wheel_name flag">
<link name="${small_wheel_name}_wheel">
<visual>
  <geometry>
    <sphere radius="${small_wheel_radius}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
  <material name="wheel_color"/>
</visual>


<collision>
 <geometry>
    <sphere radius="${small_wheel_radius}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</collision>
<xacro:sphere_inertial_matrix m="${small_wheel_mass}" r="${small_wheel_radius}"/>
<gazebo reference="${small_wheel_name}_wheel"> 
  <material>Gazebo/Red</material>
</gazebo>

</link>

<joint name="${small_wheel_name}_wheel2base_link" type="continuous">
<parent link="base_link"/>
  <child link="${small_wheel_name}_wheel"/>
  <origin xyz="${0.08*flag} 0 ${small_joint_z}"/>
  <axis xyz="0 1 0"/>
</joint>
</xacro:macro>


<xacro:small_wheel_func small_wheel_name="front" flag="1"/>
<xacro:small_wheel_func small_wheel_name="back" flag="-1"/>


</robot>