<robot name="mycamera" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:property name="camera_length" value="0.02"/>
<xacro:property name="camera_width" value="0.05"/>
<xacro:property name="camera_height" value="0.05"/>
<xacro:property name="camera_x" value="0.08"/>
<xacro:property name="camera_y" value="0.0"/>
<xacro:property name="camera_z" value="${camera_height/2+base_link_length/2}"/>
<xacro:property name="camera_mass" value="0.01"/>



<link name="camera">
<visual>
  <geometry>
    <box size="${camera_length} ${camera_width} ${camera_height}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
<material name="black"/>
</visual>

<collision>
     <geometry>
    <box size="${camera_length} ${camera_width} ${camera_height}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</collision>
<xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
<gazebo reference="camera"> 
  <material>Gazebo/Blue</material>
</gazebo>

</link>


<joint name="camera2base_link" type="fixed">
  <parent link="base_link"/>
  <child link="camera"/>
  <origin xyz="${camera_x} ${camera_y} ${camera_z}"/>
</joint>




</robot>