<robot name="mylaser" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="support_length" value="0.15"/>
<xacro:property name="support_radius" value="0.01"/>
<xacro:property name="laser_radius" value="0.03"/>
<xacro:property name="laser_length" value="0.05"/>

<xacro:property name="joint_support_x" value="0"/>
<xacro:property name="joint_support_y" value="0"/>
<xacro:property name="joint_support_z" value="${base_link_length/2+support_length/2}"/>
<xacro:property name="joint_laser_x" value="0"/>

<xacro:property name="joint_laser_y" value="0"/>
<xacro:property name="joint_laser_z" value="${support_length/2+laser_length/2}"/>
<xacro:property name="support_mass" value="0.1"/>
<xacro:property name="laser_mass" value="0.15"/>


<link name="support">
<visual>
  <geometry>
   <cylinder radius="${support_radius}" length="${support_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
<material name="yellow"/>
</visual>

<collision>
     <geometry>
   <cylinder radius="${support_radius}" length="${support_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</collision>
<xacro:cylinder_inertial_matrix m="${support_mass}" r="${support_radius}" h="${support_length}"/>
<gazebo reference="support"> 
  <material>Gazebo/Gray</material>
</gazebo>


</link>


<joint name="support2base" type="fixed">
  <parent link="base_link"/>
  <child link="support"/>
  <origin xyz="${joint_support_x} ${joint_support_y} ${joint_support_z}"/>
</joint>


<link name="laser">
<visual>
  <geometry> 
   <cylinder radius="${laser_radius}" length="${laser_length}"/>
  </geometry>
  <origin xyz="0 0 0" rpy="0 0 0"/>
<material name="black"/>
</visual>

<collision>
    <geometry> 
   <cylinder radius="${laser_radius}" length="${laser_length}"/>
  </geometry>
</collision>
<xacro:cylinder_inertial_matrix m="${laser_mass}" r="${laser_radius}" h="${laser_length}"/>
<gazebo reference="laser"> 
  <material>Gazebo/Black</material>
</gazebo>


</link>


<joint name="laser2support" type="fixed">
  <parent link="support"/>
  <child link="laser"/>
  <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}"/>
</joint>









</robot>