// Generated by gencpp from file topograph/ExecutePathRequest.msg
// DO NOT EDIT!


#ifndef TOPOGRAPH_MESSAGE_EXECUTEPATHREQUEST_H
#define TOPOGRAPH_MESSAGE_EXECUTEPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topograph
{
template <class ContainerAllocator>
struct ExecutePathRequest_
{
  typedef ExecutePathRequest_<ContainerAllocator> Type;

  ExecutePathRequest_()
    {
    }
  ExecutePathRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::topograph::ExecutePathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topograph::ExecutePathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePathRequest_

typedef ::topograph::ExecutePathRequest_<std::allocator<void> > ExecutePathRequest;

typedef boost::shared_ptr< ::topograph::ExecutePathRequest > ExecutePathRequestPtr;
typedef boost::shared_ptr< ::topograph::ExecutePathRequest const> ExecutePathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topograph::ExecutePathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topograph::ExecutePathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace topograph

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topograph::ExecutePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topograph::ExecutePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topograph::ExecutePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topograph::ExecutePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topograph::ExecutePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topograph::ExecutePathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topograph::ExecutePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::topograph::ExecutePathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::topograph::ExecutePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topograph/ExecutePathRequest";
  }

  static const char* value(const ::topograph::ExecutePathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topograph::ExecutePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 执行路径请求（空请求）\n"
;
  }

  static const char* value(const ::topograph::ExecutePathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topograph::ExecutePathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutePathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topograph::ExecutePathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::topograph::ExecutePathRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TOPOGRAPH_MESSAGE_EXECUTEPATHREQUEST_H
