// Generated by gencpp from file topograph/ExecutePathResponse.msg
// DO NOT EDIT!


#ifndef TOPOGRAPH_MESSAGE_EXECUTEPATHRESPONSE_H
#define TOPOGRAPH_MESSAGE_EXECUTEPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topograph
{
template <class ContainerAllocator>
struct ExecutePathResponse_
{
  typedef ExecutePathResponse_<ContainerAllocator> Type;

  ExecutePathResponse_()
    : success(false)  {
    }
  ExecutePathResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::topograph::ExecutePathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topograph::ExecutePathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePathResponse_

typedef ::topograph::ExecutePathResponse_<std::allocator<void> > ExecutePathResponse;

typedef boost::shared_ptr< ::topograph::ExecutePathResponse > ExecutePathResponsePtr;
typedef boost::shared_ptr< ::topograph::ExecutePathResponse const> ExecutePathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topograph::ExecutePathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topograph::ExecutePathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topograph::ExecutePathResponse_<ContainerAllocator1> & lhs, const ::topograph::ExecutePathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topograph::ExecutePathResponse_<ContainerAllocator1> & lhs, const ::topograph::ExecutePathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topograph

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topograph::ExecutePathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topograph::ExecutePathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topograph::ExecutePathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topograph::ExecutePathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topograph::ExecutePathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topograph::ExecutePathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topograph::ExecutePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::topograph::ExecutePathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::topograph::ExecutePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topograph/ExecutePathResponse";
  }

  static const char* value(const ::topograph::ExecutePathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topograph::ExecutePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 执行路径响应\n"
"bool success                     # 是否成功执行\n"
;
  }

  static const char* value(const ::topograph::ExecutePathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topograph::ExecutePathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutePathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topograph::ExecutePathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topograph::ExecutePathResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPOGRAPH_MESSAGE_EXECUTEPATHRESPONSE_H
