// Generated by gencpp from file topograph/PlanPath.msg
// DO NOT EDIT!


#ifndef TOPOGRAPH_MESSAGE_PLANPATH_H
#define TOPOGRAPH_MESSAGE_PLANPATH_H

#include <ros/service_traits.h>


#include <topograph/PlanPathRequest.h>
#include <topograph/PlanPathResponse.h>


namespace topograph
{

struct PlanPath
{

typedef PlanPathRequest Request;
typedef PlanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanPath
} // namespace topograph


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topograph::PlanPath > {
  static const char* value()
  {
    return "ac039c3aab9885e2d76b26c6b9340c81";
  }

  static const char* value(const ::topograph::PlanPath&) { return value(); }
};

template<>
struct DataType< ::topograph::PlanPath > {
  static const char* value()
  {
    return "topograph/PlanPath";
  }

  static const char* value(const ::topograph::PlanPath&) { return value(); }
};


// service_traits::MD5Sum< ::topograph::PlanPathRequest> should match
// service_traits::MD5Sum< ::topograph::PlanPath >
template<>
struct MD5Sum< ::topograph::PlanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topograph::PlanPath >::value();
  }
  static const char* value(const ::topograph::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topograph::PlanPathRequest> should match
// service_traits::DataType< ::topograph::PlanPath >
template<>
struct DataType< ::topograph::PlanPathRequest>
{
  static const char* value()
  {
    return DataType< ::topograph::PlanPath >::value();
  }
  static const char* value(const ::topograph::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topograph::PlanPathResponse> should match
// service_traits::MD5Sum< ::topograph::PlanPath >
template<>
struct MD5Sum< ::topograph::PlanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topograph::PlanPath >::value();
  }
  static const char* value(const ::topograph::PlanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topograph::PlanPathResponse> should match
// service_traits::DataType< ::topograph::PlanPath >
template<>
struct DataType< ::topograph::PlanPathResponse>
{
  static const char* value()
  {
    return DataType< ::topograph::PlanPath >::value();
  }
  static const char* value(const ::topograph::PlanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPOGRAPH_MESSAGE_PLANPATH_H
