// Generated by gencpp from file llm/WordList.msg
// DO NOT EDIT!


#ifndef LLM_MESSAGE_WORDLIST_H
#define LLM_MESSAGE_WORDLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm
{
template <class ContainerAllocator>
struct WordList_
{
  typedef WordList_<ContainerAllocator> Type;

  WordList_()
    : words()  {
    }
  WordList_(const ContainerAllocator& _alloc)
    : words(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _words_type;
  _words_type words;





  typedef boost::shared_ptr< ::llm::WordList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm::WordList_<ContainerAllocator> const> ConstPtr;

}; // struct WordList_

typedef ::llm::WordList_<std::allocator<void> > WordList;

typedef boost::shared_ptr< ::llm::WordList > WordListPtr;
typedef boost::shared_ptr< ::llm::WordList const> WordListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm::WordList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm::WordList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm::WordList_<ContainerAllocator1> & lhs, const ::llm::WordList_<ContainerAllocator2> & rhs)
{
  return lhs.words == rhs.words;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm::WordList_<ContainerAllocator1> & lhs, const ::llm::WordList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm::WordList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm::WordList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm::WordList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm::WordList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm::WordList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm::WordList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm::WordList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bd0e7dd008cf8f52a5113ba090403b7";
  }

  static const char* value(const ::llm::WordList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bd0e7dd008cf8f5ULL;
  static const uint64_t static_value2 = 0x2a5113ba090403b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::llm::WordList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm/WordList";
  }

  static const char* value(const ::llm::WordList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm::WordList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] words\n"
;
  }

  static const char* value(const ::llm::WordList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm::WordList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WordList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm::WordList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm::WordList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "words: ";
    if (v.words.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.words.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.words[i]);
    }
    if (v.words.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_MESSAGE_WORDLIST_H
